"use client";

import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Clock3, Pencil, Play, Square, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Entry = { id: string; userId: string; startedAt: string; endedAt: string | null; durationSec: number | null; note: string | null; user: { id: string; name: string | null } };
type ResponseData = { entries: Entry[]; activeTimer: { id: string; startedAt: string } | null; totalSeconds: number; currentUserId: string; canEdit: boolean };
async function request<T>(url: string, method = "GET", body?: unknown): Promise<T> {
  const response = await fetch(url, { method, headers: body === undefined ? undefined : { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
  const result = await response.json().catch(() => ({}));
  if (!response.ok) {
    const error = result.error;
    const message = typeof error === "string" ? error : error && typeof error === "object" ? Object.values(error as Record<string, unknown>).flat().find((item): item is string => typeof item === "string") : undefined;
    throw new Error(message ?? "Time tracking request failed");
  }
  return result as T;
}
function formatSeconds(seconds: number) { const safe = Math.max(0, Math.floor(seconds)); const hours = Math.floor(safe / 3600); const minutes = Math.floor((safe % 3600) / 60); const remainder = safe % 60; return `${hours}h ${String(minutes).padStart(2, "0")}m ${String(remainder).padStart(2, "0")}s`; }
function localInput(value: string | Date) { const date = new Date(value); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }

export function TimeTrackingPanel({ cardId, estimatedHours }: { cardId: string; estimatedHours: number | null }) {
  const queryClient = useQueryClient(); const queryKey = ["card-time-entries", cardId];
  const entriesQuery = useQuery({ queryKey, queryFn: () => request<ResponseData>(`/api/cards/${cardId}/time-entries`) });
  const data = entriesQuery.data; const [now, setNow] = useState(Date.now()); const [manualOpen, setManualOpen] = useState(false); const [manualStart, setManualStart] = useState(() => localInput(new Date(Date.now() - 1800000))); const [manualEnd, setManualEnd] = useState(() => localInput(new Date())); const [manualNote, setManualNote] = useState(""); const [editing, setEditing] = useState<string | null>(null); const [editStart, setEditStart] = useState(""); const [editEnd, setEditEnd] = useState(""); const [editNote, setEditNote] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!data?.activeTimer) return; const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, [data?.activeTimer]);
  const refresh = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey }), queryClient.invalidateQueries({ queryKey: ["board"] })]); };
  const run = async (action: "start" | "stop") => { setBusy(true); try { await request(`/api/cards/${cardId}/time-entries`, "POST", { action }); await refresh(); toast.success(action === "start" ? "Timer started" : "Timer stopped"); } catch (error) { toast.error(error instanceof Error ? error.message : "Timer could not be updated"); } finally { setBusy(false); } };
  const saveManual = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { await request(`/api/cards/${cardId}/time-entries`, "POST", { action: "manual", startedAt: new Date(manualStart).toISOString(), endedAt: new Date(manualEnd).toISOString(), note: manualNote.trim() || undefined }); await refresh(); setManualOpen(false); setManualNote(""); toast.success("Time entry added"); } catch (error) { toast.error(error instanceof Error ? error.message : "Time entry could not be added"); } finally { setBusy(false); } };
  const editEntry = async (entry: Entry) => { setBusy(true); try { await request(`/api/cards/${cardId}/time-entries/${entry.id}`, "PATCH", { startedAt: new Date(editStart).toISOString(), endedAt: new Date(editEnd).toISOString(), note: editNote || null }); await refresh(); setEditing(null); toast.success("Time entry updated"); } catch (error) { toast.error(error instanceof Error ? error.message : "Time entry could not be updated"); } finally { setBusy(false); } };
  const archiveEntry = async (entry: Entry) => { if (!window.confirm("Remove this entry from the time report?")) return; try { await request(`/api/cards/${cardId}/time-entries/${entry.id}`, "DELETE"); await refresh(); toast.success("Time entry removed from reports"); } catch (error) { toast.error(error instanceof Error ? error.message : "Time entry could not be removed"); } };
  if (entriesQuery.isPending) return <section className="space-y-2" aria-label="Loading time entries"><div className="h-8 animate-pulse rounded bg-muted" /><div className="h-12 animate-pulse rounded bg-muted" /></section>;
  if (entriesQuery.isError || !data) return <section className="flex items-center justify-between gap-3 rounded-lg border border-destructive/30 p-3"><p className="text-sm text-destructive">{entriesQuery.error?.message ?? "Time entries could not be loaded"}</p><Button size="sm" variant="outline" onClick={() => void entriesQuery.refetch()}>Retry</Button></section>;
  const total = data.totalSeconds + (data.activeTimer ? Math.max(0, Math.floor((now - new Date(data.activeTimer.startedAt).getTime()) / 1000)) : 0);
  return <section className="space-y-3" aria-labelledby="time-tracking-heading">
    <div className="flex flex-wrap items-center gap-2"><h3 id="time-tracking-heading" className="flex flex-1 items-center gap-2 text-sm font-semibold"><Clock3 className="h-4 w-4" />Time tracking</h3><span className="text-sm font-semibold tabular-nums">{formatSeconds(total)}</span>{data.canEdit && (data.activeTimer ? <Button size="sm" variant="destructive" disabled={busy} onClick={() => void run("stop")}><Square className="h-3.5 w-3.5" /> Stop</Button> : <Button size="sm" variant="outline" disabled={busy} onClick={() => void run("start")}><Play className="h-3.5 w-3.5" /> Start timer</Button>)}{data.canEdit && <Button size="sm" variant="outline" onClick={() => setManualOpen((value) => !value)}>Add time</Button>}</div>
    {estimatedHours !== null && <p className="text-xs text-muted-foreground">Estimate {estimatedHours}h · Actual {Math.round(total / 60) / 60}h</p>}
    {manualOpen && <form onSubmit={(event) => void saveManual(event)} className="grid gap-2 rounded-lg border bg-muted/30 p-3 sm:grid-cols-2"><label className="grid gap-1 text-xs">Start<Input type="datetime-local" value={manualStart} onChange={(event) => setManualStart(event.target.value)} required /></label><label className="grid gap-1 text-xs">End<Input type="datetime-local" value={manualEnd} onChange={(event) => setManualEnd(event.target.value)} required /></label><Input className="sm:col-span-2" value={manualNote} onChange={(event) => setManualNote(event.target.value)} maxLength={1000} placeholder="Note (optional)" aria-label="Time entry note" /><div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" size="sm" variant="ghost" onClick={() => setManualOpen(false)}>Cancel</Button><Button type="submit" size="sm" disabled={busy}>Save entry</Button></div></form>}
    {data.entries.length ? <ul className="divide-y rounded-lg border">{data.entries.map((entry) => { const seconds = entry.durationSec ?? (entry.endedAt ? Math.floor((new Date(entry.endedAt).getTime() - new Date(entry.startedAt).getTime()) / 1000) : Math.floor((now - new Date(entry.startedAt).getTime()) / 1000)); const own = data.canEdit && entry.userId === data.currentUserId && Boolean(entry.endedAt); return <li key={entry.id} className="flex flex-wrap items-center gap-x-3 gap-y-1 p-2 text-xs"><span className="min-w-24 font-medium">{entry.user.name ?? "Member"}</span><span className="text-muted-foreground">{new Date(entry.startedAt).toLocaleString()}</span><span className="ml-auto font-semibold tabular-nums">{formatSeconds(seconds)}</span>{entry.note && <span className="basis-full text-muted-foreground">{entry.note}</span>}{own && <><Button type="button" size="icon" variant="ghost" aria-label="Edit my time entry" onClick={() => { setEditing(entry.id); setEditStart(localInput(entry.startedAt)); setEditEnd(localInput(entry.endedAt!)); setEditNote(entry.note ?? ""); }}><Pencil className="h-3.5 w-3.5" /></Button><Button type="button" size="icon" variant="ghost" aria-label="Remove my time entry" onClick={() => void archiveEntry(entry)}><Trash2 className="h-3.5 w-3.5 text-destructive" /></Button></>}</li>; })}</ul> : <p className="rounded-lg border border-dashed p-4 text-sm text-muted-foreground">No time tracked yet.</p>}
    {editing && <div className="grid gap-2 rounded-lg border bg-background p-3 sm:grid-cols-2"><label className="grid gap-1 text-xs">Start<Input type="datetime-local" value={editStart} onChange={(event) => setEditStart(event.target.value)} /></label><label className="grid gap-1 text-xs">End<Input type="datetime-local" value={editEnd} onChange={(event) => setEditEnd(event.target.value)} /></label><Input className="sm:col-span-2" value={editNote} onChange={(event) => setEditNote(event.target.value)} maxLength={1000} placeholder="Note" aria-label="Edit time entry note" /><div className="flex justify-end gap-2 sm:col-span-2"><Button size="sm" variant="ghost" onClick={() => setEditing(null)}>Cancel</Button><Button size="sm" disabled={busy} onClick={() => { const entry = data.entries.find((item) => item.id === editing); if (entry) void editEntry(entry); }}>Save changes</Button></div></div>}
  </section>;
}
